### ISSUE TITLE
USER STORY: Recipe Management Admin

### ISSUE THREAD

**Issue by KaiLangen96** [KaiLangen96/dishful-discoveries#1]
As a **Site Administrator** I can **create, read, update and delete categories, recipes and comments** so that **I can manage the website**.

# Acceptance Criteria
a. As a logged in Admin, I can see a list of all catergories, recipes and comments on the admin panel.
b. As Admin I can then create, update and delete any category, recipe or comment.

# Tasks
- [x] Create Category and Recipe models.
- [x] A Recipe needs a Category to be created.
- [x] Create a superuser.
- [x] Set up the connection between Recipes and Comments.
- [x] Install summernote a better admin UX
