### ISSUE TITLE
USER STORY: Paginated Recipes

### ISSUE THREAD

**Issue by KaiLangen96** [KaiLangen96/dishful-discoveries#12]
As a **Site User** I can **scroll through a paginated list of recipes** so that **I can get a quick overview of many recipes**.

# Acceptance Criteria
a. As a Site User, I should see a paginated list of all recipes ordered by the newest first on the home page.
b. The list should consist of cards, where each card has a title, image and a short description (if available).

# Tasks
- [x] Create RecipeList class in views.py
- [x] Create homepage.html in templates
- [x] Create a UX-friendly card layout with Bootstrap 5
