### ISSUE TITLE
USER STORY: Recipe Form

### ISSUE THREAD

**Issue by KaiLangen96** [KaiLangen96/dishful-discoveries#2]
As a **Site User** I can **upload my own recipes through an easy form** so that **I can share them with other users**.

# Acceptance Criteria
a. A logged in Site User should have the option to create a recipe after clicking the "Add Recipe" button that appears after logging in on the home page and in the nav bar.
b. The click of the button should lead the Site User to a recipe creation form.
c. After filling out the form with the required data, the Site User should be able to post their recipe with the "Publish" button below.
d. With the click on the submit button, the Site User should be notified if the post was successful or not. On an error the recipe should not get posted.
e. The recipe should then be available from the User Profile page and the Recipes page.

# Tasks
- [x] Create RecipeForm in forms.py
- [x] Create AddRecipe Class in views.py
- [x] Create add_recipe.html template
- [x] Create validation steps for the recipe form to ensure correct input
- [x] Wire up URLs and templates
- [x] Create post confirmation
