### ISSUE TITLE
USER STORY: Viewing Recipes

### ISSUE THREAD

**Issue by KaiLangen96** [KaiLangen96/dishful-discoveries#4]
As a **Site User** I can **view my own recipes** so that **I can review and manage the recipes I have created**

# Acceptance Criteria
a. A logged in Site User should be able to see a "Profile" button in the nav bar.
b. The click of the button should lead the Site User to their "Profile" page.
c. This page should show all the recipes the Site User has created and some personal information if they want to.
d. On click on a specific recipe the Site User should be lead this recipes detail page.

# Tasks
- [x] Create profile.html in templates
- [x] Create a user friendly pagination to show the profiles details and recipes
- [x] Create MyRecipes in views.py
- [x] Create a hidden "Profile" button, which shows for the logged in Site User
