### ISSUE TITLE
USER STORY: User Login & Logout

### ISSUE THREAD

**Issue by KaiLangen96** [KaiLangen96/dishful-discoveries#6]
As a **Site User** I can **log in and out of my account** so that **post, comment and like recipes**

# Acceptance Criteria
## Login
a. As a Site User I should be able to find a "Login" button in the nav bar.
b. The click of the button should lead the Site User to a login page.
c. After filling in their login details the Site User should be able to log into their account.
d. A success or error message should show the Site User if the login was successful or not.
e. On correct input the Site User should be lead to the home page.

## Logout
a. As a logged in Site User I should be able to find a "Logout" button on the same postion as the former "Login" button in the nav bar.
b. The click of that button should ask the Site User once for confirmation and then log the Site User out of their account.

# Tasks
- [x] Install allauth and add it to the installed apps
- [x] Add allauth into the URLs
- [x] Add the "Login"/"Logout" button to the nav bar
- [x] Customize allauth "Login"/"Logout" templates
- [x] Create login status confirmation
