### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by KaiLangen96** [KaiLangen96/dishful-discoveries#7]
As a **Site User** I can **register myself to this website** so that **create/update/delete my own recipes and comments**.

# Acceptance Criteria
a. As a Site User I should see a  "Sign Up" button on the homepage.
b. The click of the button should lead the Site User to the SignUp page.
c. After filling in the details a new account should be created for the Site User.

# Tasks
- [x] Add a SignUp button to the nav bar, which is only visible for logged out Site Users
- [x] Create SignUp.html in templates
- [x] Create success or error messages for the registration process
