### ISSUE TITLE
USER STORY: Like Recipes

### ISSUE THREAD

**Issue by KaiLangen96** [KaiLangen96/dishful-discoveries#9]
As a **Site User** I can **"Like" a recipe** so that **I can sort out recipes I like from others**.

# Acceptance Criteria
a. As a logged in Site User I should be able to "like" a recipe with a heart icon.
b. The click on the icon should add the recipe to the Site Users "Likes" page.
c. Another click on the icon should remove the recipe from their "Likes" page.
d. A notification should appear for the Site User to confirm the adding or removing of a recipe to their liked page.

# Tasks
- [x] Add "Likes" icon to the recipe details page which only appears for logged in Site Users
- [x] Create Likes in views.py
- [x] Toggle the "Likes" icon from border to solid
